name: luz_smart_ilumina
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  get: ^4.7.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  get_storage: ^2.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/bombillo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/bombillo.png"
